# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gg00hrWH6KJOFE7HHQ38_jShqPoQ1JYQ
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np
import pandas as pd

app = FastAPI()

# Load your trained models
import os
BASE_DIR = os.path.dirname(__file__)

rf_co = joblib.load(os.path.join(BASE_DIR, "rf_co_model.joblib"))
rf_pm25 = joblib.load(os.path.join(BASE_DIR, "rf_pm25_model.joblib"))
rf_pm10 = joblib.load(os.path.join(BASE_DIR, "rf_pm10_model.joblib"))

class SensorReading(BaseModel):
    co_raw: float
    co_conv_linear_ppm: float = 0.0
    no2_raw: float = 0.0
    no2_mv: float = 0.0
    pm25_raw: float
    pm10_raw: float
    temperature: float
    humidity: float
    timestamp: str

@app.post("/predict")
def predict(reading: SensorReading):
    ts = pd.to_datetime(reading.timestamp)
    hour = ts.hour
    dow = ts.dayofweek
    no2_mv_log = np.log1p(reading.no2_mv)

    row = [
        reading.co_raw, reading.co_conv_linear_ppm, reading.no2_raw, reading.no2_mv,
        no2_mv_log, reading.pm25_raw, reading.pm10_raw, reading.temperature,
        reading.humidity, hour, dow
    ]

    co = rf_co.predict([row])[0]
    pm25 = rf_pm25.predict([row])[0]
    pm10 = rf_pm10.predict([row])[0]

    return {"co_ppm": float(co), "pm25": float(pm25), "pm10": float(pm10)}